### ISSUE TITLE
API 수정 요청

### ISSUE THREAD

**Issue by jsm8109jsm** [T-shaped-People/TCP-Backend#7]
![image](https://user-images.githubusercontent.com/105054567/186878039-7bc2ae5a-3aed-4337-86e2-baa30113941c.png)

팀 코드를 입력했을 시 팀에 들어갈 수 있게 수정해주세요.

![image](https://user-images.githubusercontent.com/105054567/186878508-611309f2-ce2d-483e-a5f2-c3df19e32f87.png)
![image](https://user-images.githubusercontent.com/105054567/186878635-b92b7f44-40fb-4396-9909-fc2589154750.png)

사진에 맞게 Create Team을 수정해주세요.

**Comment by jsm8109jsm** [comment]
또, Create Team을 했을 때 팀 코드(6자리)를 같이 반환하면 좋을 것 같네요.

**Comment by leehj050211** [comment]
팀 가입은 이미 수정되었습니다 teamId를 teamCode로 변경해주세요.

**Comment by leehj050211** [comment]
팀 코드는 팀 생성해서 나오는 id로 따로 api 요청해서 받아주세요.
팀 가입할 때 빼고는 팀 id로 api 요청을 해야합니다
